---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure elasticsearch is running
  service: name=elasticsearch enabled=yes state=started
  tags: service
