---
- name: "[REDHAT] install elasticsearch signing key"
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
  tags: repo

- name: "[REDHAT] install elasticsearch repository"
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644
  tags: repo

- name: "[REDHAT] install packages"
  yum: name={{ item }} state=present
  with_items: redhat_packages
#    - java-1.7.0-openjdk
#    - elasticsearch
  tags: package
