- name: remove default nginx site
  action: file path={{ elasticsearch_nginx_dir.confd }}/default state=absent
  notify: restart nginx

- name: copy nginx config file over to host
  template: src=nginx.conf.j2 dest={{ elasticsearch_nginx_dir.confd }}/elasticsearch.conf mode=0644 owner=root group=root
  notify: restart nginx

