---
- name: copy elasticsearch template over to host
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0640 owner=root group=root

- name: ensure elasticsearch service is running
  service: name=elasticsearch enabled=yes state=started

