- name: create ssl directory
  file: path={{ elasticsearch_nginx_dir.ssl }} state=directory mode=0755 owner=root group=root

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Texas/L=San Antonio/O=Rackspace/CN={{ elasticsearch_nginx.hostname }}" -days 3650 -keyout {{ elasticsearch_nginx_dir.ssl }}/{{ elasticsearch_nginx.hostname }}.key -out {{ elasticsearch_nginx_dir.ssl }}/{{ elasticsearch_nginx.hostname }}.crt -extensions v3_ca creates={{ elasticsearch_nginx_dir.ssl }}/{{ elasticsearch_nginx.hostname }}.crt
  notify: restart nginx

- name: create nginx htpasswd files
  htpasswd: path=/etc/nginx/conf.d/{{ elasticsearch_nginx.hostname }}.htpasswd name={{ item.username }} password={{ item.password }} owner={{ elasticsearch_nginx.user }} group={{ elasticsearch_nginx.group }} mode=0640
  with_items: elasticsearch_credentials
  notify: restart nginx
