---
- name: install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items: requirements

- name: install elasticsearch signing key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: install elasticsearch repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/0.90/debian stable main' state=present

- name: install elasticsearch and dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items: debian_packages

- name: copy elasticsearch /etc/default template over to host
  template: src=elasticsearch.j2 dest=/etc/default/elasticsearch mode=0644 owner=root group=root
